[project]
name = "pytask_slurm"
version = "0.1.0"
description = "Submit pytask tasks as SLURM jobs."
requires-python = ">=3.10"
dependencies = [
    "attrs>=21.3.0",
    "cloudpickle",
    "pytask>=0.5.2",
    "pytask-parallel",
]

[project.entry-points.pytask]
pytask_slurm = "pytask_slurm.plugin"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.sdist]
exclude = ["tests"]
only-packages = true

[tool.hatch.build.targets.wheel]
exclude = ["tests"]
only-packages = true
